#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100. displaying fizzbuzz along the way

for ((i = 1; i < 101; i++))
do
	if (( i % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	elif ((i % 3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
