#!/usr/bin/env bash
# Description
FILENAME="/etc/passwd"
while IFS=: read -r f0 f1 f2 f3 f4 f5 f6
do
  echo "The user $f0 is part of the $f1 gang, lives in $f2 and rides $f3. $f4's place is protected by the passcode $f5, more info about the user here: $f6"
done < $FILENAME
