#!/usr/bin/env bash
# Description
FILENAME="/etc/passwd"
while IFS=: read -r f0 f2 f3 f4 f5 f6 f7
do
  echo "The user $f0 is part of the $f2 gang, lives in $f3 and rides $f4. $f5's place is protected by the passcode $f6, more info about the user here: $f7"
done < $FILENAME
