#!/usr/bin/env bash
#Bash script that displays the visitor IP along with the HTTP status code from the Apache log file, displaying and ordered by number of occurences

awk '{ print $1,$9 }' apache-access.log | sort | uniq -c | sort -r
