#!/usr/bin/env bash
# This script is displaying "Best School" 9 times with Hi at the 9th lines
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	i=$(( i + 1))
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
done
