#!/usr/bin/env bash
# This script is displaying "Best School" 10 times except for 4 and 8
i=1
while [ $i -lt 10 ]
do
	echo "Best School"
	i=$(( i + 1 ))
	
		if [ $i = 4 ]
		then
			echo "bad luck"
		elif [ $i = 8 ]
		then
			echo "good luck"
		fi
done
